### ISSUE TITLE
Provide warning for missing required query fields instead of failing silently

### ISSUE THREAD

**Issue by ptboyer** [amplitude/redux-query#102]
When I was developing a query object for my `requestAsync` action to be dispatched, no errors or warnings were shown when attempting to call my request action without a required `update` field.

Because I was using the data from the request's Promise, I had no need to write any `update` functions for modifying the state with my request's response, so I forgot to add an empty `update: {}` object to my query object.

**Instead of failing silently**, It would be great to provide a `console.warn` for when a request is scrapped due missing required fields.

I suppose the same could be added to the `url` field, however that one is difficult to forget!

Cheers

**Comment by ryanashcraft** [comment]
@ptboyer Hmm… it should be throwing an error - see https://github.com/amplitude/redux-query/blob/093068d96bf18f752b46900a4abe4f3ca6114d6e/src/middleware/query-advanced.js#L66

Perhaps there's something in your setup that's swallowing the error? You can try modifying [the hello world example](https://amplitude.github.io/redux-query/#/hello-world) to repro the expected behavior:

<img width="559" alt="screen shot 2018-08-02 at 7 58 56 am" src="https://user-images.githubusercontent.com/523675/43592267-074404a6-962a-11e8-8785-463e90fc020d.png">

**Comment by ryanashcraft** [comment]
Closing this issue for now as not sure how to reproduce. Feel free to reopen if this continues to be an issue.
