### ISSUE TITLE
React redux v6 support?

### ISSUE THREAD

**Issue by laura-brouckman** [amplitude/redux-query#124]
React redux removes passing store as a prop (which connectRequest uses). Are there plans to update `redux-query` to support this version of `react-redux`?

**Comment by ptboyer** [comment]
Far out, ran into this problem just now.

Any use of `connectRequest` would throw a `Cannot read property 'dispatch' of undefined.` because it was trying to hook into `this.context.store.dispatch` from the `react-redux` context provider.

Solved by downgrading `react-redux` to `^5.1.1` before the big `6.0.0` update.

**Comment by salvoravida** [comment]
you can try this https://github.com/salvoravida/react-redux-fork 6.5.0 

Regards

**Comment by ryanashcraft** [comment]
3.0 has been published which requires react-redux v7.1.0 or later. Please see https://amplitude.github.io/redux-query/docs/upgrade-guides/v2-to-v3 for a guide on how to upgrade from redux-query to 3.0.

cc @laura-brouckman @ptboyer @salvoravida
