### ISSUE TITLE
Lazy loaded useMutation

### ISSUE THREAD

**Issue by samuelcastro** [amplitude/redux-query#172]
Is there a way to do lazy load `useMutation` with `async/await`? Something like this:

```
const [state, onMutate] = useMutation<Entities>(async (data: Data) => ({
    url: '/api',
    body: await myPromiseCall(),
  }));
```
To create the **body** of `useMutation` with the response of another api call.

It seems it does not work out of the box.

Thanks.

**Comment by samuelcastro** [comment]
Created a PR that fixes this: https://github.com/amplitude/redux-query/pull/173

Couldn't find where docs are stored in the repo though.

**Comment by samuelcastro** [comment]
Hi, still haven't heard anything? Is this project still maintained?

Thanks!

**Comment by rctbusk** [comment]
Hey @samuelcastro, actually, I should be able to answer this now. 

So, this is probably overkill adding async/await to useMutation. I say this because useMutation does not run on mount of an object, and only runs when the callback function is called. 
In the above case, this function is `onMutate`. 

If you look at the example in the docs, https://amplitude.github.io/redux-query/docs/use-mutation.
You will notice that the useMutation takes in a callback function, and this callback function is what is used when you run the `reactToComment` function. You can pass in values to this function, including the body you want to send.

So in your case, I could write the function 
`const [state, onMutate] = useMutation<Entities>((data: Data) => ({
    url: '/api',
    body: data,
  }));

// wherever you want to do the mutation
myPromiseCall().then(body => {
  onMutate(body) \\ returns a promise, so can do .then on this as well
}
`

So yes, we do not support async/await syntax, we do support promise chaining and all that comes with that, and this should solve your problem.

**Comment by samuelcastro** [comment]
This does not fix my problem because I'm using redux-query internally as part of another library, adding `async/await` is a simple fix that I've already made here: https://github.com/amplitude/redux-query/pull/173 and still is back comparable, why do you think it would be an overkill?

Thanks.

**Comment by rctbusk** [comment]
Could you provide an example of where using promises and .then does not work for you?

A code sandbox example would definitely help me understand what your issue is

**Comment by samuelcastro** [comment]
Ok, I'll ok work on it. Thanks!

**Comment by samuelcastro** [comment]
Just fyi, I was able to fix the problem without the need of an async function on in the mutation callback. I'm closing this now.
