### ISSUE TITLE
Pass body of GET requests down to superagent

### ISSUE THREAD

**Issue by acontreras89** [amplitude/redux-query#55]
`superagent` supports data for GET requests, [sending it as query parameters](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L792). I was wondering why this ability has been removed in `redux-query`'s adapter.

Instead of [_manually_ sending the body](https://github.com/amplitude/redux-query/blob/master/src/adapters/superagent.js#L24-L26), shouldn't the adapter let superagent handle the body itself?

This change is pretty straight forward. I'd create a PR myself but I wanted to first ask if there's any good reason to not have this already.

**Comment by ryanashcraft** [comment]
Good question. It's mostly an effort to try to keep things simple. You can always bring your own query stringify library without much pain. A lot of our urls look like  `/api/example-endpoint?${qs(params)}`. This is also nice because there are different ways to encode arrays and nested objects as query params. Just seems easier to support than having a bunch of different options for configuring the encoding.

**Comment by acontreras89** [comment]
@ryanashcraft I've gone ahead and created #57 so you can see how simple the change is :)

Also, note that this doesn't remove the ability to manually parse and add query parameters to your URL:

```js
import superagent from 'superagent'

const request = superagent.get('localhost?a=1', { b: 2 }) // localhost?a=1&b=2
request.query({ c: 3 }) // localhost?a=1&b=2&c=3
```
