### ISSUE TITLE
Duplicate DELETE request 

### ISSUE THREAD

**Issue by rogovdm** [amplitude/redux-query#71]
There an edge case with `DELETE` request when it is fired twice.

````javascript
const createRequest = (url, method, body) => {
    switch (method) {
        // ...
        case httpMethods.DELETE:
            return superagent.del(url, body);
        default:
            throw new Error(`Unsupported HTTP method: ${method}`);
    }
};
````

When calling `superagent.del` with `body` param `superagent` _starts the request_. And then we start it for the second time.

At this point of writing i figured out that `redux-query` is using quite old version of `superagent` lib — 1.6.1 😺  And the latest stable is 3.5.1.

Time to upgrade within v2.0?

**Comment by ryanashcraft** [comment]
@rogovdm Yes totally. I had forgotten that we were behind and now is a good opportunity to update.

With some early testing it looks like superagent 3.5.1 does not have this issue and I was able to reproduce it on the current version of redux-query. However, I couldn't find anything in the changelog to indicate that was intentional.

**Comment by rogovdm** [comment]
Thing is with `superagent.del` method. It's (v1.6.1) signature expects the second argument to be a callback, not a data (unlike other methods: put, post, ...). And after «receiving» a callback `superagent` starts executing the request. At least in the latest version the signature has changed and del accepts data property as well.

I think it's because initially `DELETE` request was treated as one without body data.

Excited about v2.0 release, will test it on my project 😸
