### ISSUE TITLE
Feature request — dynamic action types

### ISSUE THREAD

**Issue by rg4real** [amplitude/redux-query#74]
When it's tons of requests going on, it's hard to use dev-tools with a purpose of filtering.

[img](https://dl.dropboxusercontent.com/spa/sy5tiz1zn952c15/_6amudxu.png)

Can we consider adding dynamic types?

**Comment by ryanashcraft** [comment]
@rogovdm Haha I feel your pain. But I don't feel good about the idea. Is this something you've seen other libraries support? I feel like a better way to solve this problem is to get the redux log visualizer to support custom `(action) => description` transforms.

**Comment by rogovdm** [comment]
> Is this something you've seen other libraries support?

No 😸  But I feel no practical need to look up for `redux-form` actions.

> I feel like a better way to solve this problem is to get the redux log visualizer to support custom (action) => description transforms.

Thanks for idea.

**Comment by bravo-kernel** [comment]
First of all, awesome library. I'm using it to generate generic requests to various (feathersjs) endpoints and must say that I am mighty impressed 💯 . 

Hope you don't mind but... are you folks saying that it is possible to configure the log visualiser so that the various actions become more distinguishable (by e.g. using a description) ? If so, a pointer would be more than appreciated.

If not, *would reconsidering be an option*? Why I'm asking:

1. I currently don't get how to start a saga for a specific action type (could be my novice level)
2. I think it would improve the visuals a lot. A library that supports prefixing is [feathers-redux](https://github.com/feathers-plus/feathers-redux). In this screenshot it is producing results for the `messages` service/API endpoint. For the `projects` service it would become e.g. `SERVICES_PROJECTS_FIND_PENDING`


![image](https://user-images.githubusercontent.com/230500/64556989-e2537a00-d340-11e9-968c-2bf32fe0f27f.png)

I think they have chosen a pretty good default here. Things stay very consistent (and library-recognizable) because the end-user can only pass/set the (optional) service name. I can imagine something similar for redux-query:

**@@query/REQUEST_USERS_SUCCESS**
**@@query/REQUEST_PROJECTS_SUCCESS**

**Comment by rctbusk** [comment]
Hey @bravo-kernel! Sorry for the late response. Let me do some research and think about this more and get back to you!

**Comment by bravo-kernel** [comment]
No problem, thanks for giving this some thought. No rush either, take your time 👍

**Comment by karevn** [comment]
@rg4real why don't you just create a catch-all saga and then route redux-query related actions based on their query keys or meta values? You can also dispatch your custom-named actions from there, and IMO it's a much better design due to better separation of concerns.

**Comment by rctbusk** [comment]
@bravo-kernel, for now, I do not think this is something the team is going to invest in terms of new features are concerned. 

To solve your problem, I think @karevn has the right idea.
