### ISSUE TITLE
Serializing url and body could cause passwords to be stored in plain text

### ISSUE THREAD

**Issue by jth0024** [amplitude/redux-query#96]
Hello,

Correct me if I'm wrong, but I think your current approach could result in passwords being stored in plain text. Your documentation states that the default queryKey is computed by serializing the url and body. If that's the case, then a mutation that includes a new password in the body could cause that password to get serialized and stored in plain text, right?

**Comment by ryanashcraft** [comment]
@jth0024 I would think it'd only be a concern if you're running in a shared context where other untrusted scripts could access the redux state. Or you're persisting your redux state to some untrusted location.

I recommend manually providing the `queryKey` field in this case, and redux-query will use that instead of serializing the url and body. Or if you're really paranoid, you might just want to just use `fetch` or something else instead of redux-query for these sensitive requests.

**Comment by karevn** [comment]
By the way, queryKey's are quite long currently. Why not to compute some kind of hashes for them instead? It would save a decent amount of memory.

**Comment by karevn** [comment]
#110 resolves this issue by using md5 for query keys.
@jth0024 You can also generate keys by your custom code if you want.

**Comment by ryanashcraft** [comment]
Closing this issue thanks to @karevn's contribution with #110 – you can now override the default query key function. The next release (coming soon) will include this change.
